- name: "Gather hosts facts"
  hosts: linux
  gather_facts: yes
  gather_subset: "!all"
  tasks:
    - name: "Hosts affectation"
      group_by:
        key: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
    - debug:
      var: "ansible_distribution"
    - debug:
      var: "ansible_distribution_majot_version"
