- name: "Gather hosts facts"
  hosts: linux
  become: yes
  gather_facts: yes
  gather_subset: "!all"
  tasks:
    - name: "Hosts affectation"
      group_by:
        key: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
    - debug:
        var: "ansible_distribution"
    - debug:
        var: "ansible_distribution_major_version"
- name: "Update SSL on CentOS-7 machines"
  hosts: "CentOS-7"
  become: yes
  gather_facts: no
  tasks:
    - yum:
        update_cache: yes
        name: "*"
        state: "latest"
      register: out
    - debug: var=out
- name: "Update SSL on Ubuntu machines"
  hosts: "Ubuntu-14"
  become: yes
  gather_facts: no
  tasks:
    - apt:
        force_apt_get: yes
        update_cache: yes
        upgrade: yes
        autoremove: yes
      register: out
    - debug: var=out.stdout_lines
- name: "Update SSL on Kali machines"
  hosts: kali
  become: yes
  gather_facts: no
  tasks:
    - apt:
        force_apt_get: yes
        update_cache: yes
        upgrade: yes
        autoremove: yes
      register: out
    - debug: var=out.stdout_lines
