- name: "Apache Installation"
  hosts: Debian01
  become: yes
  tasks:
    - name: "Install apache package"
      apt:
        name: "apache2"
        state: "present"
    - name: "Apache configuration"
      template:
        src: "inventory.conf.j2"
        dest: "/etc/apache2/conf-available/inventory.conf"
        owner: "www-data"
        group: "www-data"
    - name: "Start apache service"
      service:
        name: "apache2"
        state: "restarted"
        enabled: yes
