- name: "Generate html file for each host"
  hosts: linux
  gather_facts: yes
  tasks:
    - name: "html file generation"
      template:
        src: "machine.html.j2"
        dest: "{{playbook_dir}}/{{inventory_hostname}}/{{inventory_hostname}}.html"
      delegate_to: localhost
