- name: "Generate html file for each host"
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    host_inventory: "Debian01"
    inventory_dir: "/var/www/html/inventory"
  tasks:
    - name: "Create template directory"
      file:
        path: "{{inventory_dir}}"
        owner: "www-data"
        group: "www-data"
        mode: "0755"
        state: "directory"
      delegate_to: "{{host_inventory}}"
      run_once: yes
    - name: "html file generation"
      template:
        src: "machine.html.j2"
        dest: "{{inventory_dir}}/{{inventory_hostname}}.html"
      delegate_to: "{{host_inventory}}"

