- name: Tranfer and execute a script
  hosts: Debian02
  become: yes
  tasks:
    - name: Transfer the script
      copy: src=test.sh dest=/home/victor mode=0777
    - name: Execute the script
      command: sh /home/victor/test.sh
      register: out
    - debug: var=out.stdout_lines

