- hosts: linux-debian-based
  become: yes
  tasks:
  - name: install all updates
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      autoclean: yes
- hosts: linux-redhat-based
  become: yes
  tasks:
  - name: install all updates
    yum:
      name: '*'
      update_cache: yes
      state: present
